"""initial

Revision ID: 2435b201a2b8
Revises: 
Create Date: 2026-09-07 08:48:45.480403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2435b201a2b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beatmaps',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('beatmapset_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_name', sa.String(length=256), nullable=False),
    sa.Column('approach_rate', sa.Float(), nullable=False),
    sa.Column('circle_size', sa.Float(), nullable=False),
    sa.Column('overall_difficulty', sa.Float(), nullable=False),
    sa.Column('hp_drain', sa.Float(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('count_circles', sa.Integer(), nullable=False),
    sa.Column('count_sliders', sa.Integer(), nullable=False),
    sa.Column('count_spinners', sa.Integer(), nullable=False),
    sa.Column('max_combo', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('star_rating_normal', sa.Float(), nullable=False),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('total_pp', sa.Float(), nullable=True),
    sa.Column('total_accuracy', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_total_pp'), ['total_pp'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beatmap_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('combo', sa.Integer(), nullable=False),
    sa.Column('mods', sa.JSON(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.BigInteger(), nullable=False),
    sa.Column('count_great', sa.Integer(), nullable=False),
    sa.Column('count_large_droplet', sa.Integer(), nullable=False),
    sa.Column('count_small_droplet', sa.Integer(), nullable=False),
    sa.Column('count_small_droplet_miss', sa.Integer(), nullable=False),
    sa.Column('count_miss', sa.Integer(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_beatmap_id'), ['beatmap_id'], unique=False)
        batch_op.create_index('ix_scores_beatmap_user', ['beatmap_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_pp'), ['pp'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_scores_pp'))
        batch_op.drop_index(batch_op.f('ix_scores_date'))
        batch_op.drop_index('ix_scores_beatmap_user')
        batch_op.drop_index(batch_op.f('ix_scores_beatmap_id'))

    op.drop_table('scores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_total_pp'))

    op.drop_table('users')
    op.drop_table('meta')
    op.drop_table('beatmaps')
    # ### end Alembic commands ###
