"""player all-maps pp

Revision ID: 577825fcd8bd
Revises: 8ff5f10d716b
Create Date: 2026-09-07 12:59:23.696841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577825fcd8bd'
down_revision = '8ff5f10d716b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pp_all', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_accuracy_all', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_total_pp_all'), ['total_pp_all'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_total_pp_all'))
        batch_op.drop_column('total_accuracy_all')
        batch_op.drop_column('total_pp_all')

    # ### end Alembic commands ###
