"""profile stats: join_date, beatmap length, rank snapshots

Revision ID: 8ff5f10d716b
Revises: 2435b201a2b8
Create Date: 2026-09-07 09:49:33.676592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff5f10d716b'
down_revision = '2435b201a2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_snapshots',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    with op.batch_alter_table('beatmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('join_date')

    with op.batch_alter_table('beatmaps', schema=None) as batch_op:
        batch_op.drop_column('length')

    op.drop_table('rank_snapshots')
    # ### end Alembic commands ###
