"""add discord_link

Revision ID: af21e322560f
Revises: 577825fcd8bd
Create Date: 2026-09-07 13:41:47.186674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af21e322560f'
down_revision = '577825fcd8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_links',
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('osu_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['osu_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('discord_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_links')
    # ### end Alembic commands ###
